### ISSUE TITLE
Proposal for Mission Statement

### ISSUE THREAD

**Issue by PeterB83** [DataForGood-Norway/read-this-first#2]

**Comment by Patechoc** [comment]
We could reuse the ones for DataForDemocracy!? 

version 1

> OUR MISSION
>
> Data for Democracy brings together an active, passionate community of people **using data to drive better decisions and improve the world in which we live**.

version 2

>  Data for Democracy's mission is **to be an inclusive community** for data scientists and technologists to volunteer and collaborate on projects that make a positive impact on society.

We could be even more inclusive and extend the "community" explicitly to anyone with ideas. They could for example lead a project even without programming skills. Designers, marketers could also help make some of those projects sustainable by transforming them into businesses.
